// packages/web/src/components/Badge.tsx
import { ReactNode } from 'react';

interface BadgeProps {
  children: ReactNode;
  variant?: 'default' | 'success' | 'warning' | 'danger' | 'info' | 'neutral';
  size?: 'sm' | 'md' | 'lg';
  dot?: boolean;
  dotColor?: string;
}

const variantStyles = {
  default: 'bg-gray-100 text-gray-700',
  success: 'bg-green-100 text-green-700',
  warning: 'bg-amber-100 text-amber-700',
  danger: 'bg-red-100 text-red-700',
  info: 'bg-blue-100 text-blue-700',
  neutral: 'bg-gray-50 text-gray-600 border border-gray-200',
};

const sizeStyles = {
  sm: 'px-2 py-0.5 text-xs',
  md: 'px-2.5 py-1 text-sm',
  lg: 'px-3 py-1.5 text-sm',
};

export function Badge({ 
  children, 
  variant = 'default', 
  size = 'sm',
  dot = false,
  dotColor,
}: BadgeProps) {
  return (
    <span 
      className={`inline-flex items-center gap-1.5 font-medium rounded-full ${variantStyles[variant]} ${sizeStyles[size]}`}
    >
      {dot && (
        <span 
          className="w-1.5 h-1.5 rounded-full"
          style={{ backgroundColor: dotColor || 'currentColor' }}
        />
      )}
      {children}
    </span>
  );
}

// Status-specific badge for orders
interface StatusBadgeProps {
  status: string;
  statusColors: Record<string, string>;
  statusLabels: Record<string, string>;
}

export function StatusBadge({ status, statusColors, statusLabels }: StatusBadgeProps) {
  const color = statusColors[status] || '#6B7280';
  const label = statusLabels[status] || status;
  
  return (
    <span
      className="px-2.5 py-1 text-sm font-medium rounded-full"
      style={{
        backgroundColor: `${color}15`,
        color: color,
      }}
    >
      {label}
    </span>
  );
}

// packages/slip-sort/frontend/src/lib/components/ui/Badge.svelte
<script>
  /** @type {'default' | 'success' | 'warning' | 'danger' | 'info' | 'primary' | 'secondary' | 'destructive'} */
  export let variant = 'default';
  /** @type {'sm' | 'md' | 'lg'} */
  export let size = 'md';
  export let dot = false;

  /** @type {Record<string, string>} */
  const variants = {
    default: 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-300',
    success: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
    warning: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400',
    danger: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
    info: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
    primary: 'bg-primary-100 text-primary-700 dark:bg-primary-900/30 dark:text-primary-400',
    secondary: 'bg-gray-200 text-gray-600 dark:bg-gray-600 dark:text-gray-300',
    destructive: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
  };

  /** @type {Record<'sm' | 'md' | 'lg', string>} */
  const sizes = {
    sm: 'px-2 py-0.5 text-xs',
    md: 'px-2.5 py-1 text-xs',
    lg: 'px-3 py-1 text-sm',
  };

  /** @type {Record<string, string>} */
  const dotColors = {
    default: 'bg-gray-400',
    success: 'bg-green-500',
    warning: 'bg-yellow-500',
    danger: 'bg-red-500',
    info: 'bg-blue-500',
    primary: 'bg-primary-500',
    secondary: 'bg-gray-400',
    destructive: 'bg-red-500',
  };

  $: classes = [
    'inline-flex items-center gap-1.5 font-medium rounded-full',
    variants[variant],
    sizes[size],
  ].join(' ');
</script>

<span class={classes} {...$$restProps}>
  {#if dot}
    <span class="w-1.5 h-1.5 rounded-full {dotColors[variant]}"></span>
  {/if}
  <slot />
</span>
